# Generated by Django 5.2.5

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('stripe_product_id', models.CharField(max_length=100, unique=True, verbose_name='ID do Produto Stripe')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produto Stripe',
                'verbose_name_plural': 'Produtos Stripe',
            },
        ),
        migrations.CreateModel(
            name='StripePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_price_id', models.CharField(max_length=100, unique=True, verbose_name='ID do Preço Stripe')),
                ('unit_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário (centavos)')),
                ('currency', models.CharField(default='brl', max_length=3, verbose_name='Moeda')),
                ('interval', models.CharField(choices=[('month', 'Mensal'), ('year', 'Anual'), ('one-time', 'Único')], verbose_name='Intervalo')),
                ('interval_count', models.PositiveIntegerField(default=1, verbose_name='Contador de Intervalo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='payments.stripeproduct', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Preço Stripe',
                'verbose_name_plural': 'Preços Stripe',
                'ordering': ['product__name', 'unit_amount'],
            },
        ),
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(max_length=100, unique=True, verbose_name='ID do Cliente Stripe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_customer', to='auth.user', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Cliente Stripe',
                'verbose_name_plural': 'Clientes Stripe',
            },
        ),
        migrations.CreateModel(
            name='StripeSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(max_length=100, unique=True, verbose_name='ID da Assinatura Stripe')),
                ('status', models.CharField(choices=[('incomplete', 'Incompleta'), ('incomplete_expired', 'Incompleta Expirada'), ('trialing', 'Período de Teste'), ('active', 'Ativa'), ('past_due', 'Vencida'), ('canceled', 'Cancelada'), ('unpaid', 'Não Paga'), ('paused', 'Pausada')], verbose_name='Status')),
                ('current_period_start', models.DateTimeField(verbose_name='Início do Período Atual')),
                ('current_period_end', models.DateTimeField(verbose_name='Fim do Período Atual')),
                ('cancel_at_period_end', models.BooleanField(default=False, verbose_name='Cancelar no Fim do Período')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='payments.stripeprice', verbose_name='Preço')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_subscriptions', to='auth.user', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Assinatura Stripe',
                'verbose_name_plural': 'Assinaturas Stripe',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StripePaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(max_length=100, unique=True, verbose_name='ID da Intenção de Pagamento Stripe')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (centavos)')),
                ('currency', models.CharField(default='brl', max_length=3, verbose_name='Moeda')),
                ('status', models.CharField(choices=[('requires_payment_method', 'Requer Método de Pagamento'), ('requires_confirmation', 'Requer Confirmação'), ('requires_action', 'Requer Ação'), ('processing', 'Processando'), ('requires_capture', 'Requer Captura'), ('canceled', 'Cancelado'), ('succeeded', 'Sucesso')], verbose_name='Status')),
                ('payment_method_types', models.JSONField(default=list, verbose_name='Tipos de Método de Pagamento')),
                ('client_secret', models.CharField(blank=True, max_length=200, verbose_name='Segredo do Cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to='auth.user', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Intenção de Pagamento Stripe',
                'verbose_name_plural': 'Intenções de Pagamento Stripe',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_event_id', models.CharField(max_length=100, unique=True, verbose_name='ID do Evento Stripe')),
                ('event_type', models.CharField(max_length=100, verbose_name='Tipo do Evento')),
                ('data', models.JSONField(verbose_name='Dados do Evento')),
                ('processed', models.BooleanField(default=False, verbose_name='Processado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Processamento')),
            ],
            options={
                'verbose_name': 'Evento de Webhook Stripe',
                'verbose_name_plural': 'Eventos de Webhook Stripe',
                'ordering': ['-created_at'],
            },
        ),
    ] 