# Generated by Django 5.2.5 on 2025-09-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stripepaymentintent',
            options={'verbose_name': 'Intenção de Pagamento Stripe', 'verbose_name_plural': 'Intenções de Pagamento Stripe'},
        ),
        migrations.AlterModelOptions(
            name='stripeprice',
            options={'verbose_name': 'Preço Stripe', 'verbose_name_plural': 'Preços Stripe'},
        ),
        migrations.AlterModelOptions(
            name='stripesubscription',
            options={'verbose_name': 'Assinatura Stripe', 'verbose_name_plural': 'Assinaturas Stripe'},
        ),
        migrations.AlterField(
            model_name='stripepaymentintent',
            name='status',
            field=models.CharField(choices=[('requires_payment_method', 'Requer Método de Pagamento'), ('requires_confirmation', 'Requer Confirmação'), ('requires_action', 'Requer Ação'), ('processing', 'Processando'), ('requires_capture', 'Requer Captura'), ('canceled', 'Cancelado'), ('succeeded', 'Sucesso')], max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='stripeprice',
            name='interval',
            field=models.CharField(choices=[('month', 'Mensal'), ('year', 'Anual'), ('one-time', 'Único')], max_length=20, verbose_name='Intervalo'),
        ),
        migrations.AlterField(
            model_name='stripesubscription',
            name='status',
            field=models.CharField(choices=[('incomplete', 'Incompleta'), ('incomplete_expired', 'Incompleta Expirada'), ('trialing', 'Período de Teste'), ('active', 'Ativa'), ('past_due', 'Vencida'), ('canceled', 'Cancelada'), ('unpaid', 'Não Paga'), ('paused', 'Pausada')], max_length=20, verbose_name='Status'),
        ),
    ]
