# Generated by Django 5.2.5 on 2025-08-15 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Gratuito'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='free', max_length=20, verbose_name='Plano')),
                ('max_shortcuts', models.PositiveIntegerField(default=50, verbose_name='Máximo de Atalhos')),
                ('ai_enabled', models.BooleanField(default=True, verbose_name='IA Habilitada')),
                ('ai_model_preference', models.CharField(default='gpt-3.5-turbo', max_length=50, verbose_name='Modelo IA Preferido')),
                ('ai_requests_used', models.PositiveIntegerField(default=0, verbose_name='Requisições IA Usadas (mês atual)')),
                ('max_ai_requests', models.PositiveIntegerField(default=100, verbose_name='Máximo de Requisições IA por Mês')),
                ('theme', models.CharField(choices=[('light', 'Claro'), ('dark', 'Escuro'), ('auto', 'Automático')], default='auto', max_length=20, verbose_name='Tema')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Notificações por Email')),
                ('total_shortcuts_used', models.PositiveIntegerField(default=0, verbose_name='Total de Atalhos Usados')),
                ('time_saved_minutes', models.PositiveIntegerField(default=0, verbose_name='Tempo Economizado (minutos)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil do Usuário',
                'verbose_name_plural': 'Perfis dos Usuários',
            },
        ),
    ]
