# Generated by Django 5.2.5 on 2025-08-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='max_ai_requests',
            field=models.IntegerField(default=100, help_text='Use -1 para ilimitado', verbose_name='Máximo de Requisições IA por Mês'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='max_shortcuts',
            field=models.IntegerField(default=50, help_text='Use -1 para ilimitado', verbose_name='Máximo de Atalhos'),
        ),
    ]
