# Generated by Django 5.2.5 on 2025-09-22 02:18

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_planpricing_planupgraderequest_subscription_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Imagem do perfil (máx. 5MB)', null=True, upload_to=users.models.user_avatar_path, verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Conte um pouco sobre você (máx. 500 caracteres)', max_length=500, verbose_name='Biografia'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='Localização'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='public_profile',
            field=models.BooleanField(default=True, help_text='Permitir que outros usuários vejam seu perfil', verbose_name='Perfil Público'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_email',
            field=models.BooleanField(default=False, help_text='Exibir email no perfil público', verbose_name='Mostrar Email'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
    ]
