# Generated by Django 5.2.5 on 2025-09-23 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_avatar_userprofile_bio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referral_bonus_earned',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor total ganho em bônus por indicações', max_digits=10, verbose_name='Bônus Ganho por Indicação'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(blank=True, help_text='Código único para indicar outros usuários', max_length=20, null=True, verbose_name='Código de Indicação'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referral_plan_upgrades',
            field=models.PositiveIntegerField(default=0, help_text='Número de indicados que fizeram upgrade de plano', verbose_name='Upgrades de Indicados'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referred_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que fez a indicação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_users', to=settings.AUTH_USER_MODEL, verbose_name='Indicado por'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_referrals',
            field=models.PositiveIntegerField(default=0, help_text='Número total de usuários indicados', verbose_name='Total de Indicações'),
        ),
    ]
