# Generated by Django 5.2.5 on 2025-09-23 08:25

from django.db import migrations
import string
import random


def populate_referral_codes(apps, schema_editor):
    """Popula códigos de indicação para perfis existentes"""
    UserProfile = apps.get_model('users', 'UserProfile')

    # Gerar códigos para todos os perfis que não possuem
    profiles_without_code = UserProfile.objects.filter(referral_code__isnull=True)

    for profile in profiles_without_code:
        # Gerar código baseado no ID do usuário
        base_code = f"{profile.user.username[:3].upper()}{profile.user.id}"
        random_chars = ''.join(random.choices(string.ascii_uppercase + string.digits, k=4))
        referral_code = f"{base_code}{random_chars}"

        # Verificar se o código já existe e gerar um novo se necessário
        counter = 0
        while UserProfile.objects.filter(referral_code=referral_code).exists():
            counter += 1
            random_chars = ''.join(random.choices(string.ascii_uppercase + string.digits, k=4))
            referral_code = f"{base_code}{random_chars}"

            # Evitar loop infinito
            if counter > 100:
                referral_code = f"{base_code}{profile.id}{random_chars}"
                break

        profile.referral_code = referral_code
        profile.save()


def reverse_populate_referral_codes(apps, schema_editor):
    """Reverter - limpar códigos de indicação"""
    UserProfile = apps.get_model('users', 'UserProfile')
    UserProfile.objects.update(referral_code=None)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_referral_system'),
    ]

    operations = [
        migrations.RunPython(
            populate_referral_codes,
            reverse_populate_referral_codes
        ),
    ]
