# Generated by Django 5.2.5 on 2025-09-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_populate_referral_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(blank=True, help_text='Código único para indicar outros usuários', max_length=20, null=True, unique=True, verbose_name='Código de Indicação'),
        ),
    ]
