# Generated by Django 5.2.5 on 2025-08-15 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Cor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Shortcut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(help_text='Ex: //email-boasvindas', max_length=50, verbose_name='Gatilho')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('expanded_content', models.TextField(blank=True, help_text='Conteúdo processado pela IA', verbose_name='Conteúdo Expandido')),
                ('expansion_type', models.CharField(choices=[('static', 'Texto Estático'), ('ai_enhanced', 'Expandido com IA'), ('dynamic', 'Dinâmico com Variáveis')], default='static', max_length=20, verbose_name='Tipo de Expansão')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('use_count', models.PositiveIntegerField(default=0, verbose_name='Contador de Uso')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Último Uso')),
                ('ai_prompt', models.TextField(blank=True, help_text='Instruções específicas para a IA expandir este conteúdo', verbose_name='Prompt para IA')),
                ('variables', models.JSONField(blank=True, default=dict, help_text='Variáveis dinâmicas no formato JSON', verbose_name='Variáveis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shortcuts', to='shortcuts.category', verbose_name='Categoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortcuts', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Atalho',
                'verbose_name_plural': 'Atalhos',
                'ordering': ['-last_used', '-use_count', 'trigger'],
                'unique_together': {('user', 'trigger')},
            },
        ),
        migrations.CreateModel(
            name='AIEnhancementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_content', models.TextField(verbose_name='Conteúdo Original')),
                ('enhanced_content', models.TextField(verbose_name='Conteúdo Expandido')),
                ('ai_model_used', models.CharField(max_length=100, verbose_name='Modelo IA Usado')),
                ('processing_time', models.FloatField(verbose_name='Tempo de Processamento (s)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shortcut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_logs', to='shortcuts.shortcut')),
            ],
            options={
                'verbose_name': 'Log de Expansão IA',
                'verbose_name_plural': 'Logs de Expansões IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShortcutUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('context', models.CharField(blank=True, help_text='Onde o atalho foi usado (app, página, etc.)', max_length=200, verbose_name='Contexto')),
                ('shortcut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_history', to='shortcuts.shortcut')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uso de Atalho',
                'verbose_name_plural': 'Usos de Atalhos',
                'ordering': ['-used_at'],
            },
        ),
    ]
