# Generated by Django 5.2.5 on 2025-09-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcuts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortcut',
            name='url_context',
            field=models.URLField(blank=True, help_text='URL do site/serviço onde este atalho é mais útil (ex: gmail.com, linkedin.com)', null=True, verbose_name='URL de Contexto'),
        ),
    ]
