# Generated by Django 5.2.5 on 2025-09-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcuts', '0002_add_url_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcut',
            name='url_context',
            field=models.CharField(blank=True, help_text='URL do site/serviço onde este atalho é mais útil (ex: gmail.com, linkedin.com)', max_length=500, null=True, verbose_name='URL de Contexto'),
        ),
    ]
